### ISSUE TITLE
build times out

### ISSUE THREAD

**Issue by Prejitha2019** [bitrise-steplib/steps-avd-manager#10]
google-services.json
Exception in thread "Device List Monitor" java.lang.NullPointerException
        at com.android.ddmlib.EmulatorConsole.checkConnection(EmulatorConsole.java:319)
        at com.android.ddmlib.EmulatorConsole.getConsole(EmulatorConsole.java:233)
        at com.android.ddmlib.DeviceMonitor.queryAvdName(DeviceMonitor.java:246)
        at com.android.ddmlib.DeviceMonitor.updateDevices(DeviceMonitor.java:218)
        at com.android.ddmlib.DeviceMonitor.access$400(DeviceMonitor.java:56)
        at com.android.ddmlib.DeviceMonitor$DeviceListUpdateListener.deviceListUpdate(DeviceMonitor.java:658)
        at com.android.ddmlib.DeviceMonitor$DeviceListMonitorTask.processIncomingDeviceData(DeviceMonitor.java:843)
        at com.android.ddmlib.DeviceMonitor$DeviceListMonitorTask.run(DeviceMonitor.java:777)
        at java.lang.Thread.run(Thread.java:745)

**Comment by Prejitha2019** [comment]
Can you please help in sorting out this issue

**Comment by ahvth-bitrise** [comment]
Hi @Prejitha2019 can you please provide a build URL for a build where this step fails? Thanks! 😄
