### ISSUE TITLE
Builds time out every time

### ISSUE THREAD

**Issue by hb0** [bitrise-steplib/steps-avd-manager#7]
**Initial setup**
- Based on [this issue](https://github.com/bitrise-steplib/steps-avd-manager/issues/6) I used **AVD-Manager 0.9.1** and **wait-for-emulator 1.0.3** which worked great for half a year.
- I can't use the "Virtual Device Testing for Android" step as I'm using multiple Android modules and flavours in combination which it does not support.

**Problem: Emulator does not respond anymore => timeout/abort**
Out of nowhere my [build](https://app.bitrise.io/app/57140e7c90eb35e5#/builds) suddenly stopped working:

1. waiting-for-emulator 1.0.3 failed but [the build](https://app.bitrise.io/build/12d3147aa3cc5f1e) timed out (not failed)

```
Waiting for emulator boot
> Checking if device booted...
Running command timed out, retry...
> Checking if device booted...
Failed to check emulator boot status, error: exit status 255
...
Total runtime: 10.9 min (!)
Timeout after 1200 seconds (!)
```

2. I tried to skip the wait-for-emulator step as I thought it's faulty but this lead to the "Device List Monitor" NPE ([build](https://app.bitrise.io/build/10e4c93c06e9202e)) in my Gradle Step with connectedAndroidTest:

```
:datacapturing:connectedProjectnameMockDebugAndroidTestException in thread "Device List Monitor" java.lang.NullPointerException
	at com.android.ddmlib.EmulatorConsole.checkConnection(EmulatorConsole.java:319)
	at com.android.ddmlib.EmulatorConsole.getConsole(EmulatorConsole.java:233)
	at com.android.ddmlib.DeviceMonitor.queryAvdName(DeviceMonitor.java:246)
	at com.android.ddmlib.DeviceMonitor.updateDevices(DeviceMonitor.java:218)
	at com.android.ddmlib.DeviceMonitor.access$400(DeviceMonitor.java:56)
	at com.android.ddmlib.DeviceMonitor$DeviceListUpdateListener.deviceListUpdate(DeviceMonitor.java:658)
	at com.android.ddmlib.DeviceMonitor$DeviceListMonitorTask.processIncomingDeviceData(DeviceMonitor.java:843)
	at com.android.ddmlib.DeviceMonitor$DeviceListMonitorTask.run(DeviceMonitor.java:777)
	at java.lang.Thread.run(Thread.java:748)
Timeout after 1200 seconds
```

3. upgrading wait-for-emulator to 1.0.4 because of [this issue](https://github.com/bitrise-steplib/steps-wait-for-android-emulator/issues/8) [succeeded to find the emulator](https://app.bitrise.io/build/fa2b72cbebdfd725) but timed out in a later step:

```
Waiting for emulator boot
> Device booted

Install missing Android Tools:
...
Ensure required Android SDK components
Timeout after 1200 seconds
```

4. Trying to use the workaround of the [currently open/new issue](https://github.com/bitrise-steplib/steps-wait-for-android-emulator/issues/13) failed, [too](https://app.bitrise.io/build/f3ac9386ab355130):

```
* daemon not running; starting now at tcp:5037
* daemon started successfully
Emulator is ready!

install-missing-android-tools:
Ensure required Android SDK components
Timeout after 1200 seconds
```

**Comment by tamasbazs** [comment]
Hi @hb0,
Sorry for the really long delay on this thread! We spent quite some time debugging the issue and we are still in the process. In the meantime, could you try the script workaround mentioned in 4. on our Android LTS stack as well (we also checked the non-LTS stack and we saw a similar issue to the one you pasted in 2. about `Device List Monitor` ?

The mentioned script, just to have it here as well: 
```
#!/usr/bin/env bash
# fail if any commands fails
set -e
# debug log
#set -x

cd $ANDROID_HOME/emulator

echo no | avdmanager create avd -n Nexus_5X_API_26 -k "system-images;android-26;google_apis;x86" --force

emulator -avd Nexus_5X_API_26 -no-window -no-audio -debug-init > /dev/null 2>&1 &

echo "Waiting emulator is ready..."

adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done; input keyevent 82'

echo "Emulator is ready!"
```

**Comment by hb0** [comment]
Hi @tamasbazs !
Looks good - I changed the build to LTS stack in the settings and it's building not again without troubles so far. ([build](https://app.bitrise.io/build/902d445377d3d6c8))

**Comment by lszucs** [comment]
Hi @hb0,

I just went through your issue's history and saw your new comment. I will happily have a look into your issue if the above script doesn't seem to be a reliable solution.

**Comment by blbradley** [comment]
This fix also worked for me. Mentioned script plus switch to LTS.

Curious, there are only a handful of system images available. How to update them? I need google-apis-playstore images for future efforts.

**Comment by lszucs** [comment]
Hi @blbradley,

You can set the components you need in the `tag` input field.

You can see an example below in the step's default configuration: https://github.com/bitrise-steplib/steps-avd-manager/blob/master/step.yml#L77

You can also set the preferred API level, if I got you correctly. :)

**Comment by blbradley** [comment]
Hey!

I was talking about when using mentioned script above, not AVD Manager step.

Here is the output of a script step with mentioned script:
```
+------------------------------------------------------------------------------+
| (6) script@1.1.5                                                             |
+------------------------------------------------------------------------------+
| id: script                                                                   |
| version: 1.1.5                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: bash                                                                |
| time: 2018-12-12T20:28:35Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
Loading local repository...                                                     
[=========                              ] 25% Loading local repository...       
[=========                              ] 25% Fetch remote repository...        
[=========                              ] 25% Fetch remote repository...        
[=========                              ] 25% Fetch remote repository...        
[=======================================] 100% Fetch remote repository...       
Error: Package path is not valid. Valid system image paths are:
system-images;android-24;default;armeabi-v7a
system-images;android-25;google_apis;armeabi-v7a
system-images;android-26;google_apis;x86
system-images;android-19;default;armeabi-v7a
system-images;android-22;default;armeabi-v7a
system-images;android-28;google_apis;x86
null
```

How can I grab google-apis-playstore images?

**Comment by hb0** [comment]
@blbradley on Ubuntu 16 LTS *system-images;android-28;google_apis;x86* is missing which I need for a specific test so I tried to install it in the script mentioned above before the *avdmanager* command:

```
cd $ANDROID_HOME/emulator
echo no | sdkmanager --install "system-images;android-28;google_apis;x86"
echo no | sdkmanager --licenses           # to accept all licences
```

But the build times out after the following:

```
All SDK package licenses accepted.
Loading local repository...                                                     
[=========                              ] 25% Loading local repository...       
[=========                              ] 25% Fetch remote repository...        
[=========                              ] 25% Fetch remote repository...        
[=========                              ] 25% Fetch remote repository...        
[=======================================] 100% Fetch remote repository...       
Auto-selecting single ABI x86
Do you wish to create a custom hardware profile? [no] Waiting emulator is ready...
* daemon not running; starting now at tcp:5037
* daemon started successfully
```

Did you find a solution yourselve?

**Comment by blbradley** [comment]
@hb0 Hey there!

I have not.

`sdkmanager` has a `--verbose` parameter. Try that.

**Comment by blbradley** [comment]
@hb0 Additionally weird: My build output from above clearly has that image.

**Comment by lszucs** [comment]
Hey @blbradley, @hb0

I recommend to open an Intercom thread on https://bitrise.io using the live chat. Just click the small message icon in the lower right corner of the page. There we can help you sort this out more efficiently! :)

**Comment by lszucs** [comment]
One quick comment though:

the original script does not install the packages, it only uses avdmanager to instantiate a virtual device.

As per the script @hb0 posted previously: ```no | sdkmanager --licenses``` inputs 'no' to the license agreements, instead of yes, which would not actually accept them, which might be an issue, from what I gather from this thread: https://github.com/NativeScript/NativeScript/issues/5667

Let me know if this helps! If not, it would be best if you guys reach out on our website through the chat and we can start investigating your build logs directly. :)

**Comment by hb0** [comment]
Just a short note: `no | sdkmanager --licences` did not work out of the box (see below).
I'll contact the chat as soon as I can free time for this. Until then I disable the API-28 depending test.

```
echo yes | sdkmanager --verbose --install "system-images;android-28;google_apis;x86"
echo yes | sdkmanager --licenses

cd $ANDROID_HOME/ && ls -alih && touch repositories.cfg

cd $ANDROID_HOME/emulator
echo no | avdmanager create avd -n Pixel_2_API_28 -k "system-images;android-28;google_apis;x86" --force
emulator -avd Pixel_2_API_26 -no-window -no-audio -debug-init > /dev/null 2>&1 &
```

```
Warning: File /root/.android/repositories.cfg could not be loaded.
Info: Preparing "Install Google APIs Intel x86 Atom System Image (revision: 7)".
[===                                    ] 10% Installing Google APIs Intel x86 A
[===                                    ] 10% Downloading x86-28_r07.zip... 
...
Info: "Install Google APIs Intel x86 Atom System Image (revision: 7)" finished.
Warning: File /root/.android/repositories.cfg could not be loaded.
[================                       ] 42% Fetch remote repository...        
[====================                   ] 52% Fetch remote repository...        
[=======================                ] 60% Fetch remote repository...        
[=======================                ] 60% Computing updates...              
[=============================          ] 75% Computing updates...              
[=============================          ] 75% Computing updates...              
[=======================================] 100% Computing updates...             
All SDK package licenses accepted.       
 84403* daemon started successfully
Timeout after 1200 seconds
```

**Comment by fehersanyi-bitrise** [comment]
@matheus-vechietin-ifood 
Could you please send us the url of this build so I can check the full logs for some more details?

**Comment by matheus-vechietin-ifood** [comment]
Hello @fehersanyi-bitrise 
here is the build url: https://app.bitrise.io/build/dadb4ad728194ddf
thanks for help

**Comment by fehersanyi-bitrise** [comment]
Hy @matheus-vechietin-ifood sorry for the long response time, if you could not solve the issue, please try running it on the LTS stack.

**Comment by apacha** [comment]
I'm also experiencing timeouts. I've changed from deprecated Android Emulator steps to this one, but I'm only getting the following timeout when running the step out-of-the-box:

```
+------------------------------------------------------------------------------+

| (4) avd-manager                                                              |
+------------------------------------------------------------------------------+
| id: avd-manager                                                              |
| version: 0.9.2                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2019-03-04T11:42:20Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
INFO[11:42:20] Start installing (golang) with apt-get       
INFO[11:42:20]  * [OK] Step dependency (go) installed, available. 
Configs:
- Version: 26
- Resolution: 240x426
- Density: 120
- Orientation: portrait
- Tag: google_apis
- ABI: x86
- Profile: Nexus 5X
- ID: emulator
- CustomCommandFlags: -no-window -no-audio -debug-init
- Overwrite: true
- CustomConfig:
disk.dataPartition.size=1024M
hw.camera.back=emulated
hw.camera.front=emulated
hw.keyboard=yes
hw.gpu.enabled=true
hw.gpu.mode=swiftshader
hw.ramSize=1536
runtime.network.latency=none
runtime.network.speed=full
showDeviceFrame=no
skin.dynamic=yes
skin.path=_no_skin
skin.path.backup=_no_skin
vm.heapSize=384
Ensure sdk packages: [tools platform-tools system-images;android-26;google_apis;x86]
- Done
Create AVD
- Done
Start emulator
Failed to boot emulator device within 300 seconds.
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | avd-manager (exit code: 1)                                    | 332 sec  |
+---+---------------------------------------------------------------+----------+
| Issue tracker: https://github.com/bitrise-steplib/steps-avd-manager/issues   |
| Source: https://github.com/bitrise-steplib/steps-avd-manager                 |
+---+---------------------------------------------------------------+----------+
```

I've checked that UI Tests of Virtual Device is enabled in the settings and enabled Bitrise Support access to the [repository](https://app.bitrise.io/app/46b5cf7adea1286f).

**Comment by fehersanyi-bitrise** [comment]
Hello @apacha 

Could you try using the custom script @tamasbazs wrote earlier on an LTS stack? 🙃

**Comment by zawadz88** [comment]
Hi,
I got it working without any major issues so I'm posting our config here in case it helps anyone.

We're using LTS stack with the following steps (bitrise.yml):

```
- avd-manager@0.9.2:
        inputs:
        - version: '25'
        - verbose_mode: 'false'
        - custom_hw_config: |-
            disk.dataPartition.size=1024M
            hw.camera.back=emulated
            hw.camera.front=emulated
            hw.keyboard=yes
            hw.gpu.enabled=true
            hw.gpu.mode=swiftshader_indirect
            hw.ramSize=2048
            runtime.network.latency=none
            runtime.network.speed=full
            showDeviceFrame=no
            skin.dynamic=yes
            skin.path=_no_skin
            skin.path.backup=_no_skin
            vm.heapSize=256
        - custom_command_flags: "-no-window -no-audio -debug-init -no-boot-anim -no-snapshot"
        - profile: 3.4in WQVGA
        title: Create & start emulator
    - wait-for-android-emulator@1.0.4:
        inputs:
        - boot_timeout: '600'
```
![screen shot 2019-03-06 at 10 04 24](https://user-images.githubusercontent.com/3322260/53868924-65dd8880-3ff7-11e9-8330-54989e88e519.png)

We are on the Elite plan though.

It's worth to mention that the emulator hangs sometimes during tests for us - happens on 2-3% of all builds. We are still investigating this.

**Comment by apacha** [comment]
No luck on my side with the custom step: Feel free to build the app yourself. https://github.com/apacha/sensor-fusion-demo

**Comment by fehersanyi-bitrise** [comment]
Hello @apacha!

Could you check this out? I made it with your repo -> https://app.bitrise.io/build/fcf78830692d0f15
using the android docler lts stack

**Comment by zawadz88** [comment]
I'm not sure if that's the issue but in my case setting `verbose_mode` to `true` was also hanging the entire step. Disabling it did the trick for me.

**Comment by apacha** [comment]
Switching to Android LTS and making sure the right artifacts were built did the trick (debug, instead of release for androidConnectedTesting).
Thanks for the assistance!

**Comment by tavour-frank** [comment]
Also running in to this issue on the Xcode 10.2.x, on macOS 10.14 (Mojave) stack. Our project uses detox for our e2e tests on ios and android, which requires a mac OS > 10.13 https://github.com/wix/Detox#environment so switching to the Android LTS is a no-go. Has anyone been able to successfully use the AVD-manager workflow on an OS stack?

**Comment by bitce** [comment]
Hi @tavour-frank! You shouldn't have to rely on the AVD Manager for detox tests, please see: https://devcenter.bitrise.io/testing/running-detox-tests-on-bitrise/

**Comment by tavour-frank** [comment]
Hey @bitce - that page is a little outdated these days; detox now supports running tests on android devices as well as ios now https://github.com/wix/Detox/blob/master/docs/More.AndroidSupportStatus.md. 

Running the tests in an ios simulator works pretty much out of the box with that guide, but getting the tests to run on android isn't as clear cut. It'd be great if there was a work-around for the AVD manager to work on an OS stack so those of us that use react-native + detox could run our suites against both ios and android to catch any issues since community packages don't always have 100% parity for both platforms

**Comment by bitce** [comment]
Hi @tavour-frank I see, thanks for pointing that out! We're definitely expanding our guide with this after the full android support is released 🙂

**Comment by MrLoh** [comment]
@bitce I am running into the same issues with react native detox tests on android and there is now official support for android on detox. Works well on my local machine.

**Comment by bitce** [comment]
Hi @MrLoh, and anyone who might still be facing an issue with emulators, can you give this script a try?

```
#!/usr/bin/env bash
# fail if any commands fails
set -e
# debug log
set -x

# write your script here
sudo $ANDROID_HOME/tools/bin/sdkmanager --update
$ANDROID_HOME/tools/bin/sdkmanager --install "emulator"
$ANDROID_HOME/tools/bin/sdkmanager --install "system-images;android-29;google_apis;x86"
echo "no" | $ANDROID_HOME/tools/bin/avdmanager --verbose create avd --force --name "pixel" --device "pixel" --package "system-images;android-29;google_apis;x86" --tag "google_apis" --abi "x86"
$ANDROID_HOME/emulator/emulator-headless @pixel -no-boot-anim -netdelay none -no-snapshot -wipe-data -verbose -show-kernel -no-audio -gpu swiftshader_indirect -no-snapshot &> /tmp/log.txt &
sleep 160
```

**Comment by MrLoh** [comment]
@bitce thanks for the thelp. The script runs through, but tests still don't run, and when remote accessing the machine, I found that `emulator @pixel` fails with `PANIC: Missing emulator engine program for 'x86' CPU`. Is there a way to confirm the emulator started, this is really hard to debug, when not being an expert in android tooling. I'd be happy to give you access to my detox project to check it out.
